import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter } from "@/app/_components/SiteFooter";

export const metadata: Metadata = {
  title: "Terms of Use | Autolisty",
  description: "Terms of Use for Autolisty.",
};

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="rounded-3xl border border-neutral-800 bg-neutral-950/70 p-6">
      <h2 className="text-sm font-semibold uppercase tracking-[0.12em] text-neutral-300">
        {title}
      </h2>
      <div className="mt-4 space-y-4 text-sm leading-7 text-neutral-300">
        {children}
      </div>
    </section>
  );
}

export default function TermsOfUsePage() {
  return (
    <main className="min-h-screen bg-[#0b0f14] text-neutral-100">
      <div className="mx-auto max-w-4xl px-5 py-8 sm:px-6 lg:px-8">
        <div className="mb-8 text-center">
          <div className="text-xs font-semibold uppercase tracking-[0.14em] text-[#f1cc61]">
            Legal
          </div>
          <h1 className="mt-3 text-3xl font-semibold text-neutral-100">
            Terms of Use
          </h1>
          <p className="mx-auto mt-3 max-w-2xl text-sm leading-7 text-neutral-400">
            These Terms of Use govern access to and use of Autolisty.
          </p>
        </div>

        <div className="space-y-5">
          <Section title="Use of the App">
            <p>
              Autolisty is provided as a workflow tool for generating listing
              content, managing creative assets, and supporting connected
              publishing workflows. You agree to use the app only for lawful and
              authorized purposes.
            </p>
          </Section>

          <Section title="User Responsibility">
            <p>
              You are responsible for the files, prompts, listing data, links, and
              third-party accounts used with the app. You are also responsible for
              reviewing generated content before publishing or distributing it.
            </p>
          </Section>

          <Section title="Third-Party Integrations">
            <p>
              The app may connect with external platforms and services. Your use of
              those services remains subject to their own terms, policies, and API
              rules. Autolisty does not control those third-party services.
            </p>
          </Section>

          <Section title="Generated Content">
            <p>
              Content generated by the app, including AI-assisted text or metadata,
              should be reviewed before use. The app owner remains responsible for
              verifying accuracy, compliance, and suitability for publication.
            </p>
          </Section>

          <Section title="Availability">
            <p>
              The app may be modified, limited, interrupted, or discontinued at any
              time. No guarantee is made that the app will always be available or
              error-free.
            </p>
          </Section>

          <Section title="Limitation of Liability">
            <p>
              To the maximum extent permitted by law, Autolisty is provided on an
              as-is and as-available basis, without warranties of any kind. The app
              owner is not liable for indirect, incidental, consequential, or
              business-related losses arising from use of the app.
            </p>
          </Section>

          <Section title="Changes to These Terms">
            <p>
              These Terms of Use may be updated from time to time. Continued use of
              the app after changes means you accept the updated terms.
            </p>
          </Section>

          <Section title="Contact">
            <p>
              For questions about these Terms of Use, please contact the app owner
              through the business contact details associated with Autolisty.
            </p>
          </Section>
        </div>

        <div className="mt-8 text-center text-sm text-neutral-500">
          <Link href="/" className="transition hover:text-neutral-300">
            Return to Autolisty
          </Link>
        </div>

        <SiteFooter />
      </div>
    </main>
  );
}
